services:
  database:
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserverPantryCollab
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperSecret1!
    ports:
      - "1433:1433"
    volumes:
      - ./Database:/var/opt/mssql/data